(package "jai-mode"
         "0.0.1"
         "Major mdoe for JAI")

(website-url "https://github.com/krig/jai-mode")
(keywords "languages")

(package-file "jai-mode.el")
(files "*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)

(depends-on "emacs" "26.3")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
